import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/layouts/Header";
import Footer from "@/app/layouts/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="allPage">
            <Header />
            {children}
        </div>
      <Footer/>
      </body>
    </html>
  );
}
